#
# 🎭 CMS-Manager SwiftLint Configuration
#
# "Where code style meets automation magic, ensuring our Swift code
# flows with elegance and consistency like a perfectly choreographed ballet."
#
# - The Spellbinding Code Style Guardian
#

# 📂 Included paths
included:
  - CMS-Manager
  - CMS-ManagerTests

# 🚫 Excluded paths
excluded:
  - Pods
  - .build
  - Packages
  - CMS-Manager.xcodeproj
  - DerivedData
  - local-assets
  - CMS-Manager/local-assets

# ⚙️ Analyzer Rules
analyzer_rules:
  - unused_declaration
  - unused_import

# ✅ Enabled Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 🚫 Disabled Rules
disabled_rules:
  - todo
  - trailing_whitespace

# ⚡ Rule Configurations

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - ID
    - URL

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - i
    - j
    - x
    - y
    - z

nesting:
  type_level:
    warning: 2
    error: 3

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

# 🎨 Custom Rules

custom_rules:
  # Encourage mystical emoji comments
  mystical_comments:
    name: "Mystical Comments"
    regex: '^\s*//\s*[A-Z]'
    message: "Consider adding an emoji to make comments more mystical"
    severity: warning

  # Discourage force unwrapping in production code
  no_force_unwrap_in_production:
    name: "No Force Unwrap"
    regex: '!\s*(?!\/\/)'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping - handle optionals gracefully"
    severity: warning
    excluded: ".*Tests\\.swift"

# 📊 Reporter
reporter: "xcode"
